### PR TITLE
Make godot-python importable even if we are not in the godot engine.

### LINKED ISSUE #174: get the godot import available in an external IDE
I want to use an external IDE (pyCharm) with godot-python but it complains obviously about the missing import of godot (and wants to download it with pip which will fail).
Do you or anybody here have an idea how to make the godot package available?

### PR DESCRIPTION
**Pull request by matheus2740**
This PR makes some checks for the availability of gdapi10 instead of trying to access it when it's null, causing a segfault.
Fixes #174 
Problem:
```
Python 3.8.3 (default, May 18 2020, 00:17:26) 
[Clang 10.0.0 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import godot
Segmentation fault      (core dumped) ./addons/pythonscript/x11-64/bin/python3
```

Importing godot from the python interpreter, without being imported as a GDNative extension cause the interpreter to segfault because pythonscript_gdapi10 was not set (NULL).
Thus, the library wasn't importable by IDEs like PyCharm or VSCode, and those weren't able to provide code completions.
With this PR, most of the builtins get their `__init__` replaced by a dummy one when gdapi10 is not available. The library will be essentially unusable because it cant interface with godot, but it imports, and that is enough for introspection and code completion.

### CODE REVIEW

**Comment by touilleMan** [comment]
Given the only usage for this is IDE autocomplete (`godot` module is just meaningless without Godot), I'd rather provide [stub files](https://www.python.org/dev/peps/pep-0484/#stub-files).
The benefit is this would be useful to plenty of IDE and static checking tools like mypy.

On top of that we could add a check in the godot module __init__ to raise an exception at loading time if gdapi is not configured so stop in an elegant way.

**Comment by matheus2740** [comment]
Yeah, I agree. Automatic generation should be possible by using mypy's stubgen (automatic pyi generator). In order for that to work tho, we would need a godot project to launch stubgen (otherwise the extension modules will not be importable and the generator will just crash). 
So we would need:
* add mypy to requirements.txt
* create simple, headless godot project that just calls mypy.stubgen and then exit
* change scons to execute this godot project and copy the .pyi files to the correct location

Honestly I'm a bit sad because this took a lot of work, but in the end I cannot see another use for it besides IDE code completion.

**Comment by touilleMan** [comment]
> Yeah, I agree. Automatic generation should be possible by using mypy's stubgen (automatic pyi generator). 

I was more thinking of generating the stub files the same way we generate builtins and bindings modules. So we should only have to change the template files to generate a `.pyi` instead of a `.pyx` ;-)

**Comment by matheus2740** [comment]
Closing in favour of #202

**Comment by touilleMan** [comment]
see #208 for the sanity check when loading godot from regular Python interpreter

**Pull request closed without merging**
