### PR TITLE
Fix typo: "i.g." -> "i.e."

### PR DESCRIPTION
**Pull request by follower**

### CODE REVIEW

**Comment by touilleMan** [comment]
Thanks for the PR !

However I think the correct form here is `e.g.` (we are giving an example of node)
`i.e.` => `id est`, "which is"
`e.g.` -> `exempli gratia`, "for example"

**Comment by follower** [comment]
You are indeed correct and I'm glad you were paying attention because apparently *I* wasn't. :D

**Comment by follower** [comment]
At least I didn't make it "e.e.". :D

**Comment by touilleMan** [comment]
thx !

**Pull request merged**
