### PR TITLE
made the CPython backend version configurable

### PR DESCRIPTION
**Pull request by swenner**
The same should probably be done for pypy.

### CODE REVIEW

**Comment by touilleMan** [comment]
Thanks for the contribution ;-)
You should run`scons black` to fix the style (the CI doesn't seem to like it right now)

**Comment by swenner** [comment]
Unfortunately black requires python 3.6 and I'm stuck at 3.5. If I could access the Travis error log I would fix it directly.

**Comment by touilleMan** [comment]
buuuut you could use the python embeded in godot to install&run black !

Anyway, I've fixed the style for you ;-)

**Comment by swenner** [comment]
Next time! Thanks :)

**Comment by touilleMan** [comment]
the project has changed a lot since this PR, closing ;-)

**Pull request closed without merging**
