### PR TITLE
Fix link target of libpython on OSX

### PR DESCRIPTION
**Pull request by ColinKinloch**
Fix for #76.
Use "install_name_tool" to change link target of libpython from "/Users/travis/build/touilleMan/godot-python/platforms/osx-64/cpython_build/lib/libpython3.6m.dylib" to "@loader_path/lib/libpython3.6m.dylib".

### CODE REVIEW

**Comment by touilleMan** [comment]
You're pretty fast @ColinKinloch !
Two things:
- Is it possible to move this fix in the `platform/osx-64/SCsub` ? this way we would avoid the unelegant `if` and keep main SConstruct clean
- Can you add yourself to the AUTHORS.rst ?

(and thanks @garyo for the review :smile: )

**Comment by ColinKinloch** [comment]
I'll look into applying this in the cpython configure flags.

**Comment by touilleMan** [comment]
@ColinKinloch Don't you think there will be a similar trouble while linking with libpypy3 on the pypy backend ?

**Comment by ColinKinloch** [comment]
Applying the same fix to the pypy backend results in this.
```
0:00:00:0249 - Can't open dynamic library: /Users/ckinloch/godot_projects/python_test/pythonscript/libpythonscript.dylib. Error: dlopen(/Users/ckinloch/godot_projects/python_test/pythonscript/libpythonscript.dylib, 2): Library not loaded: /usr/local/opt/ncurses/lib/libncursesw.6.dylib
  Referenced from: /Users/ckinloch/godot_projects/python_test/pythonscript/bin/libpypy3-c.dylib
  Reason: image not found
----------
Type:Error
Description: Can't open dynamic library: /Users/ckinloch/godot_projects/python_test/pythonscript/libpythonscript.dylib. Error: dlopen(/Users/ckinloch/godot_projects/python_test/pythonscript/libpythonscript.dylib, 2): Library not loaded: /usr/local/opt/ncurses/lib/libncursesw.6.dylib
  Referenced from: /Users/ckinloch/godot_projects/python_test/pythonscript/bin/libpypy3-c.dylib
  Reason: image not found
Time: 0:00:00:0249
C Error: Method/Function Failed, returning: ERR_CANT_OPEN
C Source: platform/osx/os_osx.mm:1308
C Function: open_dynamic_library
```
After installing ncurses with `brew install ncurses` it works.

**Comment by vkbsb** [comment]
I tried changing the lib path as suggested.. 

The following is the currest state of libpythonscript.dylib

```
otool -L libpythonscript.dylib
libpythonscript.dylib:
	pythonscript/libpythonscript.dylib (compatibility version 0.0.0, current version 0.0.0)
	@loader_path/lib/libpython3.6m.dylib (compatibility version 3.6.0, current version 3.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

this is what i got. .

andle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] 1   libsystem_platform.dylib            0x00007fff5b913f5a _sigtramp + 26
[2] 2   _cffi_backend.cpython-36m-darwin.so 0x00000001184bedf2 default_allocator + 9962
[3] 3   libpythonscript.dylib               0x0000000117a77938 _cffi_f_godot_global_get_singleton + 408
[4] 4   libpython3.6m.dylib                 0x0000000117bb44ed _PyCFunction_FastCallDict + 525
[5] 5   libpython3.6m.dylib                 0x0000000117c3cc7e call_function + 478
[6] 6   libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[7] 7   libpython3.6m.dylib                 0x0000000117c3d7b1 _PyEval_EvalCodeWithName + 2657
[8] 8   libpython3.6m.dylib                 0x0000000117c34407 PyEval_EvalCodeEx + 55
[9] 9   libpython3.6m.dylib                 0x0000000117c30f42 builtin___build_class__ + 578
[10] 10  libpython3.6m.dylib                 0x0000000117bb44af _PyCFunction_FastCallDict + 463
[11] 11  libpython3.6m.dylib                 0x0000000117c3cc7e call_function + 478
[12] 12  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[13] 13  libpython3.6m.dylib                 0x0000000117c3d7b1 _PyEval_EvalCodeWithName + 2657
[14] 14  libpython3.6m.dylib                 0x0000000117c343c0 PyEval_EvalCode + 48
[15] 15  libpython3.6m.dylib                 0x0000000117c31be6 builtin_exec + 550
[16] 16  libpython3.6m.dylib                 0x0000000117bb424d PyCFunction_Call + 205
[17] 17  libpython3.6m.dylib                 0x0000000117c3a3fc _PyEval_EvalFrameDefault + 24492
[18] 18  libpython3.6m.dylib                 0x0000000117c3d7b1 _PyEval_EvalCodeWithName + 2657
[19] 19  libpython3.6m.dylib                 0x0000000117c3df9c fast_function + 732
[20] 20  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
vvamsi@ATH017697:godot $ [21] 21  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
vvamsi@ATH017697:godot $ [22] 22  libpython3.6m.dylib                 0x0000000117c3defe fast_function + 574
[23] 23  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[24] 24  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[25] 25  libpython3.6m.dylib                 0x0000000117c3defe fast_function + 574
[26] 26  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[27] 27  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[28] 28  libpython3.6m.dylib                 0x0000000117c3defe fast_function + 574
[29] 29  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[30] 30  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[31] 31  libpython3.6m.dylib                 0x0000000117c3e343 _PyFunction_FastCallDict + 915
[32] 32  libpython3.6m.dylib                 0x0000000117b6bdda _PyObject_FastCallDict + 346
[33] 33  libpython3.6m.dylib                 0x0000000117b6cde6 _PyObject_CallMethodIdObjArgs + 518
[34] 34  libpython3.6m.dylib                 0x0000000117c59fdf PyImport_ImportModuleLevelObject + 1119
[35] 35  libpython3.6m.dylib                 0x0000000117c38c7d _PyEval_EvalFrameDefault + 18477
[36] 36  libpython3.6m.dylib                 0x0000000117c3d7b1 _PyEval_EvalCodeWithName + 2657
[37] 37  libpython3.6m.dylib                 0x0000000117c343c0 PyEval_EvalCode + 48
[38] 38  libpython3.6m.dylib                 0x0000000117c31be6 builtin_exec + 550
[39] 39  libpython3.6m.dylib                 0x0000000117bb424d PyCFunction_Call + 205
[40] 40  libpython3.6m.dylib                 0x0000000117c3a3fc _PyEval_EvalFrameDefault + 24492
[41] 41  libpython3.6m.dylib                 0x0000000117c3d7b1 _PyEval_EvalCodeWithName + 2657
[42] 42  libpython3.6m.dylib                 0x0000000117c3df9c fast_function + 732
[43] 43  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[44] 44  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[45] 45  libpython3.6m.dylib                 0x0000000117c3defe fast_function + 574
[46] 46  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[47] 47  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[48] 48  libpython3.6m.dylib                 0x0000000117c3defe fast_function + 574
[49] 49  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[50] 50  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[51] 51  libpython3.6m.dylib                 0x0000000117c3defe fast_function + 574
[52] 52  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[53] 53  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[54] 54  libpython3.6m.dylib                 0x0000000117c3e343 _PyFunction_FastCallDict + 915
[55] 55  libpython3.6m.dylib                 0x0000000117b6bdda _PyObject_FastCallDict + 346
[56] 56  libpython3.6m.dylib                 0x0000000117b6cde6 _PyObject_CallMethodIdObjArgs + 518
[57] 57  libpython3.6m.dylib                 0x0000000117c59fdf PyImport_ImportModuleLevelObject + 1119
[58] 58  libpython3.6m.dylib                 0x0000000117c38c7d _PyEval_EvalFrameDefault + 18477
[59] 59  libpython3.6m.dylib                 0x0000000117c3d7b1 _PyEval_EvalCodeWithName + 2657
[60] 60  libpython3.6m.dylib                 0x0000000117c343c0 PyEval_EvalCode + 48
[61] 61  libpython3.6m.dylib                 0x0000000117c31be6 builtin_exec + 550
[62] 62  libpython3.6m.dylib                 0x0000000117bb424d PyCFunction_Call + 205
[63] 63  libpython3.6m.dylib                 0x0000000117c3a3fc _PyEval_EvalFrameDefault + 24492
[64] 64  libpython3.6m.dylib                 0x0000000117c3d7b1 _PyEval_EvalCodeWithName + 2657
[65] 65  libpython3.6m.dylib                 0x0000000117c3df9c fast_function + 732
[66] 66  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[67] 67  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[68] 68  libpython3.6m.dylib                 0x0000000117c3defe fast_function + 574
[69] 69  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[70] 70  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[71] 71  libpython3.6m.dylib                 0x0000000117c3defe fast_function + 574
[72] 72  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[73] 73  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[74] 74  libpython3.6m.dylib                 0x0000000117c3defe fast_function + 574
[75] 75  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[76] 76  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[77] 77  libpython3.6m.dylib                 0x0000000117c3e343 _PyFunction_FastCallDict + 915
[78] 78  libpython3.6m.dylib                 0x0000000117b6bdda _PyObject_FastCallDict + 346
[79] 79  libpython3.6m.dylib                 0x0000000117b6cde6 _PyObject_CallMethodIdObjArgs + 518
[80] 80  libpython3.6m.dylib                 0x0000000117c59fdf PyImport_ImportModuleLevelObject + 1119
[81] 81  libpython3.6m.dylib                 0x0000000117c38c7d _PyEval_EvalFrameDefault + 18477
[82] 82  libpython3.6m.dylib                 0x0000000117c3d7b1 _PyEval_EvalCodeWithName + 2657
[83] 83  libpython3.6m.dylib                 0x0000000117c343c0 PyEval_EvalCode + 48
[84] 84  libpython3.6m.dylib                 0x0000000117c31be6 builtin_exec + 550
[85] 85  libpython3.6m.dylib                 0x0000000117bb424d PyCFunction_Call + 205
[86] 86  libpython3.6m.dylib                 0x0000000117c3a3fc _PyEval_EvalFrameDefault + 24492
[87] 87  libpython3.6m.dylib                 0x0000000117c3d7b1 _PyEval_EvalCodeWithName + 2657
[88] 88  libpython3.6m.dylib                 0x0000000117c3df9c fast_function + 732
[89] 89  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[90] 90  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[91] 91  libpython3.6m.dylib                 0x0000000117c3defe fast_function + 574
[92] 92  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[93] 93  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[94] 94  libpython3.6m.dylib                 0x0000000117c3defe fast_function + 574
[95] 95  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[96] 96  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[97] 97  libpython3.6m.dylib                 0x0000000117c3defe fast_function + 574
[98] 98  libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[99] 99  libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[100] 100 libpython3.6m.dylib                 0x0000000117c3e343 _PyFunction_FastCallDict + 915
[101] 101 libpython3.6m.dylib                 0x0000000117b6bdda _PyObject_FastCallDict + 346
[102] 102 libpython3.6m.dylib                 0x0000000117b6cde6 _PyObject_CallMethodIdObjArgs + 518
[103] 103 libpython3.6m.dylib                 0x0000000117c59fdf PyImport_ImportModuleLevelObject + 1119
[104] 104 libpython3.6m.dylib                 0x0000000117c38c7d _PyEval_EvalFrameDefault + 18477
[105] 105 libpython3.6m.dylib                 0x0000000117c3d7b1 _PyEval_EvalCodeWithName + 2657
[106] 106 libpython3.6m.dylib                 0x0000000117c343c0 PyEval_EvalCode + 48
[107] 107 libpython3.6m.dylib                 0x0000000117c31be6 builtin_exec + 550
[108] 108 libpython3.6m.dylib                 0x0000000117bb424d PyCFunction_Call + 205
[109] 109 libpython3.6m.dylib                 0x0000000117c3a3fc _PyEval_EvalFrameDefault + 24492
[110] 110 libpython3.6m.dylib                 0x0000000117c3d7b1 _PyEval_EvalCodeWithName + 2657
[111] 111 libpython3.6m.dylib                 0x0000000117c3df9c fast_function + 732
[112] 112 libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[113] 113 libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[114] 114 libpython3.6m.dylib                 0x0000000117c3defe fast_function + 574
[115] 115 libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[116] 116 libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[117] 117 libpython3.6m.dylib                 0x0000000117c3defe fast_function + 574
[118] 118 libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[119] 119 libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[120] 120 libpython3.6m.dylib                 0x0000000117c3defe fast_function + 574
[121] 121 libpython3.6m.dylib                 0x0000000117c3cc59 call_function + 441
[122] 122 libpython3.6m.dylib                 0x0000000117c3a088 _PyEval_EvalFrameDefault + 23608
[123] 123 libpython3.6m.dylib                 0x0000000117c3e343 _PyFunction_FastCallDict + 915
[124] 124 libpython3.6m.dylib                 0x0000000117b6bdda _PyObject_FastCallDict + 346
[125] 125 libpython3.6m.dylib                 0x0000000117b6cde6 _PyObject_CallMethodIdObjArgs + 518
[126] 126 libpython3.6m.dylib                 0x0000000117c59fdf PyImport_ImportModuleLevelObject + 1119
[127] 127 libpython3.6m.dylib                 0x0000000117c38c7d _PyEval_EvalFrameDefault + 18477
[128] 128 libpython3.6m.dylib                 0x0000000117c3d7b1 _PyEval_EvalCodeWithName + 2657
[129] 129 libpython3.6m.dylib                 0x0000000117c343c0 PyEval_EvalCode + 48
[130] 130 libpythonscript.dylib               0x0000000117a55c0c _cffi_initialize_python + 220
[131] 131 libpythonscript.dylib               0x0000000117a55821 _cffi_start_python + 65
[132] 132 libpythonscript.dylib               0x0000000117a5575f _cffi_start_and_call_python + 31
[133] 133 libpythonscript.dylib               0x0000000117a54a52 pybind_init + 50

**Comment by ColinKinloch** [comment]
The stack trace shows that libpython3.6m.dylib is being loaded fine.
I think this is a separate issue.

**Comment by touilleMan** [comment]
@ColinKinloch :candy: :fireworks: :champagne: 

btw I had to correct the octal notation (`0660` -> `0o660`) which is no longer valid in Python3

**Pull request merged**
