### PR TITLE
Use correct type and function names when creating pool arrays

### PR DESCRIPTION
**Pull request by garyo**
The correct names have underscores.

### CODE REVIEW

**Comment by garyo** [comment]
I'm not sure what went wrong with the Travis build but it doesn't seem to be my change... ?

**Comment by garyo** [comment]
I tried the Travis build again and it failed the same way -- before even running SCons. It fails on OSX updating with brew. Did anything change in the Travis config?

**Comment by touilleMan** [comment]
I think to recall I saw something on twitter about brew switching it default python package to 3 (and so removing python3 as a valid package), according to the documentation (http://docs.python-guide.org/en/latest/starting/install3/osx/) we should do `brew install python` to get python 3 now

**Comment by touilleMan** [comment]
master fixed, can you rebase this PR ?

**Comment by garyo** [comment]
Rebased. I also added some unit tests.

**Comment by touilleMan** [comment]
:tada: :fireworks:

**Pull request merged**
