### PR TITLE
Use Godot 3.2.3 stable in CI

### PR DESCRIPTION
**Pull request by touilleMan**

### CODE REVIEW

**Comment by gustavi** [comment]
Look's good ! Is it possible to merge it and release a new version of Godot-Python ?

**Comment by touilleMan** [comment]
Hi @gustavi !

As a matter of fact, I'm currently working on a better way to distribute Godot-Python (see https://github.com/touilleMan/godot-python-install-manager, however I've still got a lot of uncommited stuff on my computer...).

The current release on asset store mechanism is a hassle so I don't want to do another releases there.
However if you want I can do a build on github (that you'll be able to install by manually downloading it and unzip), what do you think ?

**Comment by gustavi** [comment]
I look at the project, really interesting !

If you can trigger a build it will be awesome but I can wait for the next release else.

**Comment by touilleMan** [comment]
@gustavi release 0.50.0 is here https://github.com/touilleMan/godot-python/releases/tag/v0.50.0 ^^

**Pull request merged**
